SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 600
SCREEN_TITLE = "GridWorld"

CHARACTER_SCALING = 1
TILE_SCALING = 0.5
COIN_SCALING = 0.5

AGENT_LIST_NAME = "Agents"
FLOOR_LIST_NAME = "Floor"
TARGET_LIST_NAME = "Targets"
CELL_LIST_NAME = "Cells"

PLAYER_MOVEMENT_SPEED = 5
PLAYER_JUMP_SPEED = 17
GRAVITY = 1